language: python
# Python versions to test
python:
    - "3.7"
# Command to install dependencies
install:
    - python setup.py install
    - pip install --upgrade pytest
# Command to run tests
script:
    - cd tests/unit
    - pytest
